### ISSUE TITLE
Error Type 'NSAttributedStringKey' (aka 'NSString') has no member 'foregroundColor'

### ISSUE THREAD

**Issue by aminmahdi** [cgoldsby/TvOSMoreButton#11]
We have fount error:

1) Type 'NSAttributedStringKey' (aka 'NSString') has no member 'foregroundColor'
2) Type 'NSAttributedStringKey' (aka 'NSString') has no member 'foregroundColor'

 in " TvOSMoreButton.swift"

Can you help me to resolve it ?

**Comment by xdenneboom** [comment]
I have the same issue

**Comment by cgoldsby** [comment]
Hi @aminmahdi and @xdenneboom, here is some information that might help:

Release 1.1.0+ now requires Xcode 9 but there are a few things you _may_ have to do depending on whether your project is running Swift 3.2 or Swift 4.

The [release page](https://github.com/cgoldsby/TvOSMoreButton/releases/tag/1.1.0) and [changelog](https://github.com/cgoldsby/TvOSMoreButton/blob/master/CHANGELOG.md) have more information.

If your main project has been migrated to Swift 4, i.e. SWIFT_VERSION is 4.0 in "Build Settings", then updating your Podfile to use `TvOSMoreButton` 1.1.0+ should work without any changes.

However, if your project has not been migrated to Swift 4 and is using **Swift 3.2**, then you need to update the SWIFT_VERSION to 4.0 just for the `TvOSMoreButton` pod (see  [release page](https://github.com/cgoldsby/TvOSMoreButton/releases/tag/1.1.0) for instructions.)

What version of Swift are you using?

Hopefully, one of these steps will solve these compile issues. Let me know how things go.

**Comment by aminmahdi** [comment]
tq i have fix it.

**Comment by cgoldsby** [comment]
That's fantastic @aminmahdi! I am glad things are working for you. Can this issue be closed?

**Comment by aminmahdi** [comment]
yes. thank you for ur reply
