### ISSUE TITLE
"... MORE"

### ISSUE THREAD

**Issue by LeandroGitHung** [cgoldsby/TvOSMoreButton#17]
Hi there, great library.

Please tell me... How can i change "... MORE"?
I want to change to "... NEXT", or something like.

TY!

**Comment by cgoldsby** [comment]
Hi @LeandroGitLee, try setting the `trailingText` property. [TvOSMoreButton.swift#L65](https://github.com/cgoldsby/TvOSMoreButton/blob/8ab624fb1cbf011a9565294de0e5c9be7406e6c7/Source/Public/Views/TvOSMoreButton.swift#L65)

``` swift
tvOSMoreButton.trailingText = "NEXT"
```

Please let me know if that does not work. Thanks :)

**Comment by cgoldsby** [comment]
Hi @LeandroGitLee,

I noticed a small bug today: In the current version, the trailing text will only update after you set the text.

```swift
// As a work around set the trailing text before the text
tvOSMoreButton.trailingText = "NEXT"
tvOSMoreButton.text = "your text"
```

Thanks for reporting this bug. I will have it fixed in the next version. 🙇

**Comment by cgoldsby** [comment]
Version [1.1.3](https://github.com/cgoldsby/TvOSMoreButton/releases/tag/1.1.3) has been released. 🎉
 
 Thanks for using the `TvOSMoreButton` ❤️
