### ISSUE TITLE
Right to left language support

### ISSUE THREAD

**Issue by furkanhatipoglu** [cgoldsby/TvOSMoreButton#18]
There is no option to set text alignment. I am working with Arabic language. I have to change "label"  which is a private variable.

**Comment by cgoldsby** [comment]
@furkanhatipoglu, Thank you for your interest in TvOSMoreButton.

I am not too familiar with right-left languages. 

Do the label just need `label.textAlignment = .natural`?

**Comment by furkanhatipoglu** [comment]
I prefer a variable like textColor and font to adjust manually. I can pull request if you want.

**Comment by cgoldsby** [comment]
Sure, all PRs are welcomed. But, I don't really understand the request. I am curious about the right-left language support and am interested in learning more.

There exist open variables for `textColor` and `font` already. Would those work for you? There might be a bug where they need to be set before setting the `text`.

**Comment by cgoldsby** [comment]
Fixed in #20 and release 1.1.4 was published to CocoaPods. 🚀 

 Thanks for the hard work!
