### ISSUE TITLE
variable names

### ISSUE THREAD

**Issue by furkanhatipoglu** [cgoldsby/TvOSMoreButton#19]
Thank you for this library but emojis makes it difficult to understand. They are meaningless and not reachable easily. For example: 

<img width="595" alt="screen shot 2018-09-26 at 16 33 11" src="https://user-images.githubusercontent.com/24944616/46083410-11152680-c1aa-11e8-9659-ae359c79b918.png">

**Comment by cgoldsby** [comment]
Hi @furkanhatipoglu, thank you for your feedback. Emojis are pictures and pictures are worth a thousand words. 😄 🖼

I do not consider them meaningless and provide enough context given the internal file scope in which they are used. Sorry, but I do not have future plans for changing the variable name.
