### ISSUE TITLE
Reproducing TVML like _TVButtonLockup in UIKit?

### ISSUE THREAD

**Issue by RefusedFlow** [cgoldsby/TvOSMoreButton#2]
Hi 👋🏻

Really nice project! Definitely going to be using this in a project we're working on. Thought I'd ask but do you have any plans to recreate `_TVButtonLockup` buttons in UIKit with working labels as the way it's been done in TVML?

![tvml](https://cloud.githubusercontent.com/assets/20913312/23761755/c8c7e4fc-04eb-11e7-865b-6cbe3acf47f9.png)

**Comment by cgoldsby** [comment]
Hi @tvOSPopcorn, thank you for your interest in this project. Sorry, I have no plans at the moment to recreate `_TVButtonLockup` buttons in UIKit.
