### ISSUE TITLE
Swift 4.2?

### ISSUE THREAD

**Issue by robbiet480** [cgoldsby/TvOSMoreButton#22]
Are there any near term plans to support Swift 4.2 and Xcode 10? The two issues that are stopping me are operators that have been removed (such as `&~` and `|=`). Other remaining issues are mostly renames such as `NSAttributedStringKey` to `NSAttributedString.Key`.

**Comment by cgoldsby** [comment]
@robbiet480, thank you for your interest in TvOSMoreButton. 🙇

 I released TvOSMoreButton ([1.2.0](https://cocoapods.org/pods/TvOSMoreButton)) which has support for Swift 4.2 and XCode 10.  🚀
