### ISSUE TITLE
Button stays in focused appearance when it isn't focused

### ISSUE THREAD

**Issue by OPoliukhovych** [cgoldsby/TvOSMoreButton#24]
### What did you do
Focus on TvOSMoreButton
Press remote touch surface to select button and hold, do not release remote "button" 
While remote button still not released move focus to another focusable element. Another element is focused 
Release remote button
### What did you expect to happen?
After switching focus to another element, TvOSMoreButton should stay in unfocused appearance - no highlight
### What happened instead?
After focus switched to another element, TvOSMoreButton becomes highlighted

-----------

I'm sure the reason is that method `applyPressUpAppearance()` called without checking `isFocused == true`

**Comment by cgoldsby** [comment]
Hi @OPoliukhovych, 

Thank you for your interesting in the `TvOSMoreButton` and a very well written bug report. I apologize for any trouble this bug has caused you. I understand how difficult and frustrating debugging focus problems can be on tvOS.

I published release [1.2.1](https://github.com/cgoldsby/TvOSMoreButton/releases/tag/1.2.1) with a fix for this bug. 🚀 

❤️

**Comment by OPoliukhovych** [comment]
Hi @cgoldsby,

Thank you for lightning fast fix⚡️
