### ISSUE TITLE
Installation Section

### ISSUE THREAD

**Issue by lfarah** [cgoldsby/TvOSMoreButton#3]
Hey, your library is really interesting.

The only problem I found was the ```README.md```, which lacks an ```Installation Section```
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to easily create an ```Installation Section```
If you want, I can help you to organize the lib.

What are your thoughts? 😄

**Comment by lfarah** [comment]
Please fix this before we can approve[your PR on AwesomeiOS](https://github.com/vsouza/awesome-ios/pull/1549)

**Comment by cgoldsby** [comment]
Thank you @lfarah for your README template. It was extremely helpful. 

I've added an `Installation Section`. 👍
