### ISSUE TITLE
Build fails while compiling for tvOS 11

### ISSUE THREAD

**Issue by gustavolessa23** [cgoldsby/TvOSMoreButton#7]
Hi,

Since my Apple TV updated itself to tvOS 11, I've been trying to make PopcornTimeTV work again.
Unfortunately, during compilation this version of TvOSMoreButton causes two errors:

- Type 'NSAttributedStringKey' (aka 'NSString') has no member 'foregroundColor'
- Cannot convert value of type '[NSAttributedStringKey : Any]' (aka 'Dictionary<NSString, Any>') to expected argument type '[String : Any]?'

Any idea how to fix it? I'm still trying to find something online, but it's too specific.

Thank you very much,
Gustavo

EDIT: Using the previous version it compiled just fine, but it would be nice to understand how to fix the latest version.

**Comment by cgoldsby** [comment]
Hi @gustavolessadublin, here is some information that might help:

Release 1.1.0 now requires Xcode 9 but there are a few things you _may_ have to do depending on whether your project is running Swift 3.2 or Swift 4.

The [release page](https://github.com/cgoldsby/TvOSMoreButton/releases/tag/1.1.0) and [changelog](https://github.com/cgoldsby/TvOSMoreButton/blob/master/CHANGELOG.md) have more information.

If your main project has been migrated to Swift 4, i.e. SWIFT_VERSION is 4.0 in "Build Settings", then updating your Podfile to use `TvOSMoreButton` 1.1.0 should work without any changes.

However, if your project has not been migrated to Swift 4 and is using **Swift 3.2**, then you need to update the SWIFT_VERSION to 4.0 just for the `TvOSMoreButton` pod (see  [release page](https://github.com/cgoldsby/TvOSMoreButton/releases/tag/1.1.0) for instructions.)

Hopefully, one of these steps will solve these compile issues. Let me know how things go.

**Comment by cgoldsby** [comment]
Hi @gustavolessadublin , did that information help? Can we close this issue?

**Comment by gustavolessa23** [comment]
Thanks for your reply!
I am actually using the previous version of this pod.
I noticed that the project is still using Swift 3.2, but before that I had have already success compiling using the previous version.

Thanks again for your help!
Gustavo
